apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Apply labels to group components in OpenShift topology
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    labelSelector: "app.kubernetes.io/name=grafana"
  patch: |-
    - op: add
      path: /metadata/labels/app.kubernetes.io~1part-of
      value: grafana
- target:
    group: apps
    version: v1
    kind: DaemonSet
    labelSelector: "app.kubernetes.io/name=vector"
  patch: |-
    - op: add
      path: /metadata/labels/app.kubernetes.io~1part-of
      value: vector
- target:
    labelSelector: "app.kubernetes.io/name=loki"
  patch: |-
    - op: add
      path: /metadata/labels/app.kubernetes.io~1part-of
      value: loki
- target:
    labelSelector: "app=minio"
  patch: |-
    - op: add
      path: /metadata/labels/app.kubernetes.io~1part-of
      value: loki
- target:
    labelSelector: "app.kubernetes.io/part-of=memberlist"
  patch: |-
    - op: replace
      path: /metadata/labels/app.kubernetes.io~1part-of
      value: loki

commonAnnotations:
  ignore-check.kube-linter.io/drop-net-raw-capability: |
    "Vector runs requires access to socket."
  ignore-check.kube-linter.io/run-as-non-root: |
    "Vector runs as Root and attach host Path."
  ignore-check.kube-linter.io/sensitive-host-mounts: |
    "Vector runs requires certain host mounts to watch files being created by pods."

resources:
- ../base
- loki-secret.yaml

generators:
- vector-helm-generator.yaml
- loki-helm-generator.yaml
- grafana-helm-generator.yaml
